apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: egovboot01
  name: egovboot01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: egovboot01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: egovboot01
    spec:
      containers:
      - image: brandon9999/egovboot01:v1.0.0
        name: egovboot01
        ports:
        - containerPort: 8080
        resources: {}
status: {}