apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: egov01
  name: egov01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: egov01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: egov01
    spec:
      containers:
      - image: brandon9999/egov01:v1.0.0
        name: egov01
        ports:
        - containerPort: 8080
        resources: {}
status: {}